spring.application.name=todo-backend
# 数据库连接
spring.datasource.url=jdbc:mysql://localhost:3306/todo_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=zhongzhi

# JPA 配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
